//// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class TestTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    driver = new ChromeDriver();
//    js = (JavascriptExecutor) driver;
//    vars = new HashMap<String, Object>();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void test() {
//    driver.get("http://localhost/addressbook/");
//    driver.manage().window().setSize(new Dimension(1920, 1040));
//    driver.findElement(By.linkText("home")).click();
//    driver.findElement(By.id("2")).click();
//    driver.findElement(By.cssSelector(".left:nth-child(8) > input")).click();
//    assertThat(driver.switchTo().alert().getText(), is("Delete 1 addresses?"));
//    driver.switchTo().alert().accept();
//    driver.findElement(By.linkText("home")).click();
//    driver.findElement(By.linkText("Logout")).click();
//    driver.findElement(By.name("user")).sendKeys("admin");
//    driver.findElement(By.name("pass")).sendKeys("r@78bJM=45");
//  }
//}
